// <auto-generated />
using System;
using HubService.Data.EntityModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HubService.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HubService.Data.EntityModel.Facility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AllergiesEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("DemographicsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("EHRDataFormat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EHRDataFormatVersion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EHRVendorName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("EMPI")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FacilityName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FacilityType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("LabsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("MedsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("MultiFacility")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("VitalsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Facility");
                });
#pragma warning restore 612, 618
        }
    }
}
